import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import { PrismaClient } from '@prisma/client'
import router from 'next/router'
import { useSession } from 'next-auth/react'
import Image from 'next/image'

const prisma = new PrismaClient()

export const getServerSideProps: GetServerSideProps = async () => {
  const posts = await prisma.post.findMany()

  return {
    props: {
      posts: [...posts.map(post => {
        const { title, cover, desc, tags, id } = post
        return { title: title, desc: desc, id: id, cover: cover, tags: tags }
      })]
    }
  }
}

const Home: NextPage = ({ posts }: any) => {

  const { data: session }: any = useSession()

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {session &&
        <div className='p-3'>
          {posts && posts.map((post: any) => {

            return <article onClick={() => router.push('/posts/[id]', `/posts/${post.id}`)} key={post.id} className="p-3 rounded-md  my-2 max-w-md ">
              <img src={post.cover} className=' rounded-lg ' />
              <h1 className='text-3xl w-full text-left font-bold'>{post.title}</h1>
              <span className='w-full text-gray-600 text-left'>{post.tags}</span>
              <p className='text-gray-800 font-mono'>{post.desc}</p>
            </article>
          })}
        </div>}

    </div>
  )
}

export default Home
